
package painel.de.senhas.guiche;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Interface_Guiche extends javax.swing.JFrame {

    private String ip;
    private int porta;
    
    public Interface_Guiche() {
        
        setVisible(true);
        initComponents();
    }
    
    public void Interface_Guiche (String ip, String porta){
        this.ip = ip;
        this.porta = Integer.parseInt(porta);       
    }
    
    public void sendMessage(String codigo, String guiche) {
        
        String msgIn;
        String msgOut;
        String senha = exibeSenha.getText();
        
        try {          
            msgOut = codigo;
            msgOut = msgOut +";";
            msgOut = msgOut + guiche;
            msgOut = msgOut + ";";
            msgOut = msgOut + senha;
            
            System.out.println("Tentativa de conexão em "+this.ip+":"+this.porta+"...");
            Socket socket = new Socket(this.ip, this.porta);
            System.out.println("Conexão bem sucessida");
 
            ObjectOutputStream output = new ObjectOutputStream(socket.getOutputStream());
            output.writeObject(msgOut);
            System.out.println("Enviado ao servidor: "+msgOut);
            output.flush();
            
            ObjectInputStream input = new ObjectInputStream(socket.getInputStream());
            
                msgIn = (String) input.readObject();
                System.out.println("Recebido do servidor: "+msgIn);
                exibeSenha.setText(msgIn);
            
        } catch (IOException e) { 
            JOptionPane.showMessageDialog(null, "Falha na conexão, não foi possiível enviar a mensagem ao servidor");
            System.exit(0);
            e.getStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Interface_Guiche.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    static ActionListener atualizaRelogio = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            // Assumes clock is a custom component
            //jLabel1.setText(String.valueOf(System.currentTimeMillis()));
            // OR
            // Assumes clock is a JLabel
           DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
           Date date = new Date();
           hora.setText(dateFormat.format(date));
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        hora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chama = new javax.swing.JButton();
        encerra = new javax.swing.JButton();
        relatorio = new javax.swing.JButton();
        numGuiche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        exibeSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName(""); // NOI18N

        jInternalFrame1.setTitle("JAVN Tecnologia em Atendimento");
        jInternalFrame1.setVisible(true);

        hora.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("SENHA CHAMADA:");

        chama.setText("Chamar");
        chama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaActionPerformed(evt);
            }
        });

        encerra.setText("Encerrar Atendimento");
        encerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerraActionPerformed(evt);
            }
        });

        relatorio.setText("Relatório");
        relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioActionPerformed(evt);
            }
        });

        numGuiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numGuicheActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Nº do Guichê:");

        exibeSenha.setEditable(false);
        exibeSenha.setBackground(new java.awt.Color(255, 255, 255));
        exibeSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exibeSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        exibeSenha.setText("Aguardando Senha");
        exibeSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibeSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(chama)
                                .addGap(49, 49, 49)
                                .addComponent(encerra)
                                .addGap(50, 50, 50)
                                .addComponent(relatorio)))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(exibeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numGuiche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exibeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chama)
                    .addComponent(relatorio)
                    .addComponent(encerra))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioActionPerformed
        // TODO add your handling code here:
        sendMessage("1003", numGuiche.getText()); //relatorio
    }//GEN-LAST:event_relatorioActionPerformed

    private void encerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerraActionPerformed
        // TODO add your handling code here:
        sendMessage("1002", numGuiche.getText()); //encerra
    }//GEN-LAST:event_encerraActionPerformed

    private void chamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaActionPerformed
        // TODO add your handling code here:
        sendMessage("1001", numGuiche.getText()); //chama
    }//GEN-LAST:event_chamaActionPerformed

    private void numGuicheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numGuicheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numGuicheActionPerformed

    private void exibeSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibeSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exibeSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chama;
    private javax.swing.JButton encerra;
    private javax.swing.JTextField exibeSenha;
    private static javax.swing.JLabel hora;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numGuiche;
    private javax.swing.JButton relatorio;
    // End of variables declaration//GEN-END:variables
}